---
apiVersion: v1
kind: Pod
metadata:
  name: privileged-simple-pod
  annotations:
    container.apparmor.security.beta.kubernetes.io/privileged-simple-pod: "runtime/default"
    seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: privileged-simple-pod
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1000
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]

