---
# Namespace here refers to the container namespaces, not kubernetes
apiVersion: v1
kind: Pod
metadata:
  name: privileged-namespace-pod
spec:
  securityContext:
    fsGroup: 2000
    supplementalGroups: [3000]
  serviceAccountName: restricted-service-account
  automountServiceAccountToken: false
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: privileged-namespace-container
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
        requests:
          cpu: "50m"
          memory: "64Mi"
      securityContext:
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
        seccompProfile:
          type: RuntimeDefault

